#!/bin/bash

# This file is useful for development purposes because
# it allows you to run TypeScript files without having
# to add the --loader option every time.

# Usage:

# ./node --version
# ./node bin/test.ts
# ./node --inspect bin/test.ts

# Usage with "sh" or "bash":

# sh node --version
# sh node bin/test.ts
# sh node --inspect bin/test.ts

# Node.js executable with all arguments required to run the application.
node="node --loader=ts-node/esm --experimental-import-meta-resolve --no-warnings"

$node "$@"
