name: 'Questions / Help 💬'
description: If you have questions, please check Discord or StackOverflow.
title: '[Please read the message below]'
labels: ['question']
body:
  - type: markdown
    attributes:
      value: |
        ## Questions and Help 💬

        This issue tracker is reserved for bug reports and feature proposals.

        For anything else, such as questions or getting help, please see:

        - [The Athenna help page](https://athenna.io/help)
        - [Our `#help` channel in Discord](https://discord.gg/j6FKKQQrW9)
        - The [AthennaIO](https://stackoverflow.com/questions/tagged/AthennaIO) tag on [StackOverflow](https://stackoverflow.com/questions/ask)
  - type: checkboxes
    id: no-post
    attributes:
      label: |
        Please do not submit this issue.
      description: |
        :bangbang: &nbsp; This issue will be closed. :bangbang:
      options:
        - label: I understand
          required: true
